language: python

python:
  - 3.6
  
before_install:
  # Here we download miniconda and create our conda environment
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - hash -r
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p $MINICONDA
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - conda env create -f testenv.yml -v
  - source activate testenv
  
script:
  - pytest
  # if you do not want to check the output as such but make sure the
  # notebook works only use --nbval-lax
  - pytest --nbval notebooks/00_explore-data.ipynb